import os
print("Downloading")
print(' ')
print('_'*40)

os.system('pip install webbrowser')
os.system('pip install pyfiglet')
os.system('pip install requests')
os.system('pip install os')
os.system('pip install random')
os.system('pip install json')
os.system('pip install threading')
os.system('pip install secrets')
os.system('pip install uuid')
os.system('pip install colorama')
os.system('pip install time')
os.system('pip install datetime')
os.system('pip install secrets')
os.system('pip install user_agent')
os.system('pip install sys')
os.system('pip install sleep')
os.system('pip install random')
os.system('pip install uuid4')
os.system('pip install user_agent')
os.system('pip install token_hex')
os.system('pip install Fore')
os.system('pip install choice')
os.system('pip install time')
os.system('pip install mm')
os.system('pip install webbrowser')
os.system('pip install Style')

os.system('pip install n')

os.system('cls' if os.name == 'nt' else 'clear') 
print("_"*40)
print('  ') 
print('Installed ')